"""empty message

Revision ID: ad2521f5ed4d
Revises: 8d367cad8e7e
Create Date: 2020-05-23 20:10:40.763531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2521f5ed4d'
down_revision = '8d367cad8e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_img',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, comment='id唯一值'),
    sa.Column('fid', sa.Integer(), nullable=True, comment='商品id'),
    sa.Column('img', sa.String(length=100), nullable=False, comment='商品图片'),
    sa.Column('status', sa.Integer(), nullable=True, comment='1表示激活，0表示没有激活'),
    sa.ForeignKeyConstraint(['fid'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_img')
    # ### end Alembic commands ###
