"""'addComment'

Revision ID: e044153d41c0
Revises: 9cabd74e2d7b
Create Date: 2020-05-30 23:39:28.332768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e044153d41c0'
down_revision = '9cabd74e2d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_comment',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, comment='唯一标识'),
    sa.Column('member_id', sa.Integer(), nullable=False, comment='用户的id'),
    sa.Column('order_id', sa.Integer(), nullable=True, comment='订单id'),
    sa.Column('content', sa.String(length=255), nullable=False, comment='评价的内容'),
    sa.Column('is_delete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('position', sa.Integer(), nullable=True, comment='排序'),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['pay_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_comment')
    # ### end Alembic commands ###
